FROM python:3.12

# Include the (future) directory of the Poetry executable to the PATH
ENV PATH="/opt/poetry/bin:$PATH"

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python -

# Copy the poetry.lock and pyproject.toml
COPY ./poetry.lock /app/poetry.lock
COPY ./pyproject.toml /app/pyproject.toml
WORKDIR /app

# Install the dependencies
RUN poetry config virtualenvs.create false && poetry lock && poetry install

# Copy the repo
COPY . /app

# RUN cp -r /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages-copy
